require: rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Security/Open:
  Exclude:
    - app/services/parser.rb

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 3

Metrics/AbcSize:
  Exclude:
    - app/services/dispatcher.rb
