require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Security/Open:
  Exclude:
    - app/services/base_parser.rb

RSpec/MessageSpies:
  EnforcedStyle: receive
