version: 2
jobs:
  build:
    working_directory: ~/site-parser
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          TESTOPTS: "--ci-dir=/tmp/test-results"
          APP_ENV: test
    steps:
      - checkout

      - type: cache-restore
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}

      - run: sudo gem install bundler:2.1.4
      - run: bundle install --path vendor/bundle

      - type: cache-save
        key: sinatra-demo-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - type: shell
        command: bundle exec lefthook run pre-commit
